# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 800

# Menu dimensions
PAUSE_MENU_WIDTH = 400
PAUSE_MENU_HEIGHT = 400

# Button dimensions
MAIN_MENU_BUTTON_WIDTH = 200
MAIN_MENU_BUTTON_HEIGHT = 50

OPTIONS_MENU_SMALL_BUTTON_WIDTH = 50
OPTIONS_MENU_SMALL_BUTTON_HEIGHT = 50

OPTIONS_MENU_BACK_BUTTON_WIDTH = 100
OPTIONS_MENU_BACK_BUTTON_HEIGHT = 50

PAUSE_MENU_BUTTON_WIDTH = 200
PAUSE_MENU_BUTTON_HEIGHT = 50

# Tile size
TILE_SIZE = 20
